import { Injectable, signal } from '@angular/core';

export type Lang = 'en' | 'es';

const TRANSLATIONS: Record<Lang, Record<string, string>> = {
  en: {
    // ── Navigation ──────────────────────────────────────────
    nav_dashboard: 'Dashboard',
    nav_workOrders: 'Work Orders',
    nav_history: 'History',
    nav_users: 'Users',
    nav_support: 'Support',
    nav_logout: 'Logout',
    nav_devices: 'Devices',
    nav_mapRadiation: 'Radiation Map',
    nav_alarms: 'Alarms',
    nav_profile: 'My Profile',
    nav_mySchedule: 'My Schedule',
    nav_techPortal: 'Technician Portal',
    nav_techTagline: 'Vigilance & Control',

    // ── Topbar ──────────────────────────────────────────────
    topbar_brand: 'EmSafe',
    topbar_role: 'System Admin',
    topbar_role_tech: 'Technician',

    // ── Login ────────────────────────────────────────────────
    login_email: 'Email Address',
    login_emailPlaceholder: 'alex@emsafe.com',
    login_password: 'Password',
    login_forgotPassword: 'Forgot Password?',
    login_remember: 'Remember this device',
    login_signIn: 'Sign In',
    login_or: 'OR',
    login_google: 'Sign in with Google',
    login_error: 'Invalid email or password.',
    login_required: 'Please enter your email and password.',
    login_footer: '© 2026 EmSafe Technologies. All rights reserved.',

    // ── Tech Schedule ────────────────────────────────────────
    tech_sched_title: 'Technician Portal',
    tech_sched_subtitle: 'Field Operations & Control',
    tech_sched_week: 'Week',
    tech_sched_day: 'Day',
    tech_sched_filters: 'Filters',
    tech_sched_today: 'Today',
    tech_sched_noTasks: 'No tasks scheduled',
    tech_sched_priorityTask: 'PRIORITY TASK',
    tech_sched_priorityTasks: 'PRIORITY TASKS',
    tech_sched_noPriority: 'No urgent pending tasks.',
    tech_sched_weekProgress: 'WEEK PROGRESS',
    tech_sched_tasksCompleted: 'Tasks Completed',

    // ── Tech Work Orders ─────────────────────────────────────
    tech_wo_search: 'Search by client name or ID...',
    tech_wo_allOrders: 'All Orders',
    tech_wo_serviceType: 'Service Type',
    tech_wo_export: 'Export Report',

    // ── Tech Work Order Detail ───────────────────────────────
    tech_detail_startJob: 'Start Job',
    tech_detail_saveChanges: 'Save Changes',
    tech_detail_markCompleted: 'Mark as Completed',
    tech_detail_generalInfo: 'General Info',
    tech_detail_clientContact: 'Client Contact',
    tech_detail_serviceInfo: 'Service Info',
    tech_detail_sensorInstall: 'Sensor Installation (Required)',
    tech_detail_numSensors: 'Number of sensors installed',
    tech_detail_sensorType: 'Sensor Type',
    tech_detail_uploadProof: 'Upload Installation Proof',
    tech_detail_dragDrop: 'Drag and drop or click to upload photos',
    tech_detail_sensorCheck: 'Sensor Check',
    tech_detail_techNotes: 'Technician Notes',
    tech_detail_updateStatus: 'Update Status',
    tech_detail_callClient: 'Call Client',
    tech_detail_emailClient: 'Email Client',
    tech_detail_activityLog: 'ACTIVITY LOG',
    tech_detail_scheduledDate: 'Scheduled Date',
    tech_detail_priority: 'Priority',
    tech_detail_requiredTools: 'Required Tools',
    tech_detail_expectedSensors: 'Expected:',
    tech_detail_accessInstructions: 'Access Instructions',
    tech_detail_locationMap: 'Location Map',
    tech_detail_deviceCheck: 'Device Check',
    tech_detail_maintActions: 'Maintenance Actions',
    tech_detail_deviceRemoval: 'Device Removal',
    tech_detail_uploadEvidence: 'Upload Evidence',
    tech_detail_devicesRequiring: 'Devices Requiring Maintenance',
    tech_detail_clientDevices: 'Client Devices',
    tech_detail_sensorInfo: 'Sensor Information',
    tech_detail_deviceName: 'Device Name',
    tech_detail_serial: 'Serial Number',
    tech_detail_observation: 'Observation',
    tech_detail_removed: 'Removed',
    tech_detail_action: 'Action',
    tech_detail_description: 'Description',
    tech_detail_device: 'Device',
    tech_detail_completionDate: 'Completion Date',
    tech_detail_evidence: 'Evidence',
    tech_detail_noDevices: 'No devices.',
    tech_detail_addDeviceHint: 'Click + to add an installed sensor.',
    tech_detail_discoverTitle: 'Discover Sensors (Required)',
    tech_detail_discoverHint: 'Power on the sensors on site — they appear here as they report. Pick the ones in front of you (the live reading reacts when you move the sensor), then name them.',
    tech_detail_discoverEmpty: 'No sensors detected yet. Power on a sensor and wait for it to report.',
    tech_detail_live: 'Live',
    tech_detail_lastSeen: 'last seen',
    wod_title: 'Work Order',

    // ── Common buttons ──────────────────────────────────────
    btn_cancel: 'Cancel',
    btn_create: 'Create',
    btn_update: 'Save Changes',
    btn_save: 'Save Client',
    btn_saveChanges: 'Save changes',
    dev_createDevice: 'Create Device',
    btn_submit: 'Submit',
    btn_edit: 'Edit',
    btn_delete: 'Delete',
    btn_backToList: 'Back to List',
    btn_applyFilters: 'Apply Filters',
    btn_exportCsv: 'Export CSV',
    btn_exportReport: 'Export Report',
    btn_viewAll: 'View All',
    btn_add: 'Add',

    // ── Common statuses ─────────────────────────────────────
    status_completed: 'Completed',
    status_inProgress: 'In progress',
    status_pending: 'Pending',
    status_cancelled: 'Cancelled',
    status_active: 'Active',
    status_inactive: 'Inactive',
    status_maintenance: 'Maintenance',

    // ── Common table headers ─────────────────────────────────
    th_orderId: 'Order ID',
    th_type: 'TYPE',
    th_client: 'CLIENT',
    th_location: 'LOCATION',
    th_date: 'DATE',
    th_technician: 'TECHNICIAN',
    th_status: 'STATUS',
    th_actions: 'ACTIONS',
    th_siteLocation: 'SITE LOCATION',
    th_name: 'Name',
    th_role: 'Role',
    th_email: 'Email',
    th_completionDate: 'Completion Date',
    th_clientSite: 'Client / Site',
    th_serviceType: 'Service Type',
    th_leadTech: 'Lead Technician',

    // ── Dashboard ────────────────────────────────────────────
    dash_title: 'System Overview',
    dash_subtitle: 'Real-time monitoring of electromagnetic radiation and field operations.',
    dash_newWorkOrder: 'New Work Order',
    dash_totalSensors: 'TOTAL SENSORS',
    dash_totalDevices: 'DEVICES',
    dash_activeClients: 'ACTIVE CLIENTS',
    dash_totalUsers: 'USERS',
    dash_pendingTasks: 'PENDING TASKS',
    dash_workOrders: 'WORK ORDERS',
    dash_criticalAlerts: 'CRITICAL ALERTS',
    dash_alarmsCount: 'ALARMS',
    dash_systemActivity: 'System Activity',
    dash_serviceHistory: 'Service History',
    dash_serviceHistoryHint: 'Work orders by type over 30 days',
    dash_activityHint: 'Work orders generated vs completed over 30 days',
    dash_last30Days: 'Last 30 Days',
    dash_radiationTrends: 'Radiation Trends',
    dash_radiationHint: 'Avg. Levels (µT)',
    dash_currentAvg: 'Current Avg.',
    dash_safetyThreshold: 'Safety Threshold',
    dash_safeMsg: 'All sensors within safety limits.',
    dash_latestOrders: 'Latest Work Orders',
    dash_alerts: 'System Alerts',

    // ── Work Orders list ─────────────────────────────────────
    wo_title: 'Work Orders',
    wo_subtitle: 'Manage and track electromagnetic sensor deployments and field service logs.',
    wo_createNew: 'Create New',
    wo_searchPlaceholder: 'Search work orders, clients or tech ID...',
    wo_typeAll: 'Type: All',
    filter_all: 'All',
    wo_installation: 'Installation',
    wo_maintenance: 'Maintenance',
    wo_collection: 'Collection',
    wo_statusAll: 'Status: All',
    wo_showing: 'Showing 1-10 of 124 orders',
    wo_avgTime: 'AVG. COMPLETION TIME',
    wo_regional: 'REGIONAL ACTIVITY',
    wo_cancel: 'Cancel Order',
    wo_cancelReason: 'Cancellation Reason',
    wo_cancelReasonEquip: 'Equipment issue',
    wo_cancelReasonClient: 'Client request',
    wo_cancelReasonWeather: 'Weather conditions',
    wo_cancelReasonOther: 'Other',
    wo_cancelSuccess: 'Work order cancelled.',
    wo_selectReason: 'Select reason',
    wo_sortBy: 'Sort by',
    wo_sortDate: 'Soonest scheduled',
    wo_sortCreated: 'Newest added',
    wo_deleteConfirm: 'Are you sure you want to delete this work order?',
    wo_edit: 'Edit Order',

    // ── New Work Order form ──────────────────────────────────
    wo_new_breadcrumb: 'Work Orders › Create New',
    wo_new_title: 'New Work Order',
    wo_new_editBreadcrumb: 'Work Orders › Edit',
    wo_new_editTitle: 'Edit Work Order',
    wo_new_subtitle: 'Register a new electromagnetic safety inspection or sensor maintenance task.',
    wo_new_sectionTitle: 'Work Order Details',
    wo_new_type: 'Work Order Type',
    wo_new_selectType: 'Select Type...',
    wo_new_clientName: 'Client Name',
    wo_new_searchClient: 'Search client database...',
    wo_new_location: 'Location Address',
    wo_new_locationPlaceholder: 'Search address in Peru...',
    wo_new_scheduledDate: 'Scheduled Date',
    wo_new_scheduledTime: 'Scheduled Time',
    wo_new_assignedTech: 'Assigned Technician',
    wo_new_selectTech: 'Select Technician...',
    wo_new_notes: 'Notes',
    wo_new_notesPlaceholder: 'Detailed description of the required service or observed anomalies...',
    wo_new_pickLocation: 'Pick Location on Map',
    wo_new_pickLocationHint: 'Click anywhere on the map to select the exact location.',
    wo_new_noLocationSelected: 'No location selected — click on the map',
    wo_new_confirmLocation: 'Confirm Location',

    // ── History ──────────────────────────────────────────────
    hist_title: 'Work Orders History',
    hist_subtitle: 'Completed and Cancelled Work orders',
    hist_dateRange: 'Date Range',
    hist_type: 'Type',
    hist_technician: 'Technician',
    hist_allTypes: 'All Types',
    hist_allPersonnel: 'All Personnel',
    hist_showing: 'Showing 1 - 5 of 142 results',
    hist_from: 'From',
    hist_to: 'To',
    hist_clearDates: 'Clear',
    hist_view: 'View Details',
    hist_detail_title: 'Order Details',
    hist_detail_completedBy: 'Completed by',
    hist_detail_completionDate: 'Completion Date',
    hist_detail_notes: 'Admin Notes',
    hist_detail_cancellationReason: 'Cancellation Reason',
    hist_detail_sensorsInstalled: 'Sensors Installed',
    hist_detail_techNotes: 'Technician Notes',
    hist_detail_noNotes: 'No notes recorded.',

    // ── Users / Team Management ──────────────────────────────
    users_title: 'Team Management',
    users_subtitle: 'Manage admins, technicians and registered clients of the platform.',
    users_totalUsers: 'TOTAL USERS',
    users_activeNow: 'ACTIVE NOW',
    users_activeSub: 'Users',
    users_activeClients: 'ACTIVE CLIENTS',
    users_activeClientsSub: 'Registered clients',
    users_inactiveClients: 'INACTIVE CLIENTS',
    users_inactiveClientsSub: 'Need attention',
    users_clearFilters: 'Clear filters',
    users_viewClient: 'View Client',
    users_activate: 'Activate account',
    vc_title: 'Client Profile',
    vc_devices: 'Devices',
    vc_noDevices: 'This client has no devices.',
    vc_notFound: 'Client not found.',
    users_pendingApproval: 'PENDING APPROVAL',
    users_pendingSub: 'Action Required',
    users_activated: 'User activated',
    users_activateFail: 'Could not activate the user',
    users_deleted: 'User deleted successfully',
    users_confirmDelete: 'Are you sure you want to delete this user?',
    users_systemHealth: 'SYSTEM HEALTH',
    users_healthSub: 'Optimal',
    users_allUsers: 'All Users',
    users_admins: 'Admins',
    users_technicians: 'Technicians',
    users_clients: 'Clients',
    users_searchPlaceholder: 'Search team members...',
    users_addModalTitle: 'Add New User',
    users_addModalDesc: 'Select the type of user you want to add to the platform.',
    users_addAdmin: 'Admin',
    users_addAdminDesc: 'System operator with full access',
    users_addTechnician: 'Technician',
    users_addTechDesc: 'Field service operator',
    users_addClient: 'Client',
    users_addClientDesc: 'External entity with sensor access',
    users_joinDate: 'Join Date',

    // ── Create Admin form ────────────────────────────────────
    admin_breadcrumb: 'Users › Create New Admin',
    admin_title: 'Create New Admin',
    admin_editTitle: 'Edit Admin',
    admin_sectionTitle: 'Admin Details',
    admin_sectionDesc: 'Enter the information to provision a new system operator.',

    // ── Create Technician form ───────────────────────────────
    tech_breadcrumb: 'Users › Create New Technician',
    tech_title: 'Create New Technician',
    tech_editTitle: 'Edit Technician',
    tech_sectionTitle: 'Technician Details',
    tech_sectionDesc: 'Enter the information to provision a new field operator.',

    // ── Common form fields ───────────────────────────────────
    form_fullName: 'Full Name',
    form_emailAddress: 'Email Address',
    form_phone: 'Phone Number',
    form_password: 'Password',
    form_confirmPassword: 'Confirm Password',
    form_additionalNotes: 'Additional Notes',
    form_notesPlaceholder: 'Enter any administrative notes regarding this user account...',
    form_activationMsg: 'Newly created users will receive an activation email with their temporary credentials and instructions for the first login security setup.',
    form_status: 'Account Status',
    form_statusActive: 'Active (check to activate, uncheck for inactive)',
    form_statusInactive: 'Inactive',
    form_statusHint: 'If unchecked, the account will be created as inactive.',

    // ── Edit Client form ─────────────────────────────────────
    client_edit_breadcrumb: 'Users › Edit Client',
    client_new_breadcrumb: 'Users › New Client',
    client_edit_title: 'Edit Client',
    client_new_title: 'New Client',
    client_edit_subtitle: 'Register or update a client entity.',
    client_type: 'Client Type',
    client_company: 'Company',
    client_individual: 'Individual',
    client_info: 'Client Information',
    client_companyName: 'Company Name',
    client_taxId: 'Tax ID',
    client_ruc: 'RUC',
    client_industry: 'Industry',
    client_selectIndustry: 'Select an industry...',
    client_fullName: 'Full Name',
    client_docId: 'DNI / Document Number',
    client_location: 'Location',
    client_address: 'Address',
    client_city: 'City',
    client_country: 'Country',
    client_primaryContact: 'Primary Contact',
    client_contactName: 'Contact Name',
    client_contactEmail: 'Email',
    client_contactPhone: 'Phone',
    client_sensorInfo: 'Sensor Information',
    client_numSensors: 'Number of Installed Sensors',
    client_sensorType: 'Sensor Type',
    client_appAccess: 'App Access',
    client_enableApp: 'Enable App Access',
    client_accessEmail: 'Access Email',
    client_prefilled: 'Prefilled from primary contact',
    client_statusNotes: 'Status & Notes',
    client_initialStatus: 'Status',
    client_internalNotes: 'Internal Notes',
    client_internalPlaceholder: 'Enter any specific requirements or background information here...',
    client_active: 'Active',
    client_inactive: 'Inactive',

    // ── Profile page ─────────────────────────────────────────────────────────────
    profile_title: 'My Profile',
    profile_subtitle: 'View and update your account information.',
    profile_personalInfo: 'Personal Information',
    profile_security: 'Security',
    profile_currentPassword: 'Current Password',
    profile_newPassword: 'New Password',
    profile_confirmNew: 'Confirm New Password',
    profile_changePassword: 'Change Password',
    profile_savedOk: 'Profile updated successfully.',
    profile_pwOk: 'Password changed successfully.',
    profile_pwError: 'Failed to change password. Check your current password.',

    // ── Devices page ─────────────────────────────────────────────────────────────
    dev_title: 'Devices',
    dev_subtitle: 'Manage electromagnetic sensors and monitoring equipment.',
    dev_addDevice: 'Add Device',
    dev_editDevice: 'Edit Device',
    dev_name: 'Device Name',
    dev_type: 'Type',
    dev_location: 'Location',
    dev_status: 'Status',
    dev_serial: 'Serial Number',
    dev_installDate: 'Install Date',
    dev_selectType: 'Select type...',
    dev_sensor: 'Sensor',
    dev_gateway: 'Gateway',
    dev_monitor: 'Monitor',
    dev_controller: 'Controller',
    dev_plug: 'Plug',
    dev_actuator: 'Actuator',
    dev_active: 'Active',
    dev_inactive: 'Inactive',
    dev_inMaintenance: 'In Maintenance',
    dev_requiresMaintenance: 'Requires Maintenance',
    dev_collecting: 'Collecting',
    dev_confirmDelete: 'Delete this device?',
    dev_noDevices: 'No devices found.',
    dev_client: 'Associated Client',
    dev_viewClient: 'View Client',
    dev_createWorkOrder: 'Create Work Order',
    dev_searchPlaceholder: 'Search by name or serial...',
    dev_filterAll: 'All',
    dev_filterByClient: 'Client: All',
    dev_filterByType: 'Type: All',
    dev_filterByStatus: 'Status: All',

    // ── Alarms page ───────────────────────────────────────────────────────────────
    alarm_title: 'Alarms',
    alarm_subtitle: 'Monitor and manage system alerts and notifications.',
    alarm_addAlarm: 'New Alarm',
    alarm_resolve: 'Resolve',
    alarm_resolved: 'Resolved',
    alarm_unresolved: 'Unresolved',
    alarm_all: 'All',
    alarm_sensorAlarms: 'Sensor Alarms',
    alarm_systemAlerts: 'System Alerts',
    alarm_allClients: 'All Clients',
    alarm_titleField: 'Title',
    alarm_description: 'Description',
    alarm_type: 'Type',
    alarm_confirmDelete: 'Delete this alarm?',
    alarm_noAlarms: 'No alarms found.',
    alarm_icon: 'Icon class (optional)',
    alarm_danger: 'Critical',
    alarm_info: 'Info',
    alarm_success: 'Success',
    alarm_warning: 'Warning',
    alarm_recipients: 'Recipients',
    alarm_allUsers: 'All users',
    alarm_specificUsers: 'Specific users',
    alarm_detail_title: 'Alarm Details',
    alarm_client: 'Client',
    alarm_filterByClient: 'Client: All',
    alarm_sensor: 'Sensor',
    alarm_time: 'Time',
    alarm_sensorPlaceholder: 'e.g. #LM-012 (optional)',
    alarm_clientHint: 'Hold Ctrl/Cmd to select multiple clients.',
    btn_close: 'Close',

    // ── Radiation Map page ────────────────────────────────────────────────────────
    map_title: 'Radiation Map',
    map_subtitle: 'Geographic distribution of electromagnetic radiation readings.',
    map_sensor: 'Sensor',
    map_value: 'Value (µT)',
    map_date: 'Date',
    map_location: 'Location',
    map_noData: 'No radiation data available.',
    map_listView: 'List View',
    map_legend: 'Legend',
    map_safe: 'Safe',
    map_caution: 'Caution',
    map_danger: 'Danger',
    map_client: 'Client',
    map_zone: 'Zone / Area',
    map_clickHint: 'Click a marker to see client details',

    // ── Topbar ──────────────────────────────────────────────
    topbar_preferences: 'Preferences',
    topbar_darkMode: 'Dark Mode',
    topbar_fontSize: 'Font Size',
    topbar_fontSmall: 'Small',
    topbar_fontMedium: 'Medium',
    topbar_fontLarge: 'Large',
    topbar_myProfile: 'My Profile',
    topbar_recentActivity: 'Recent Activity',
    topbar_noActivity: 'No recent activity',

    btn_saveProfile: 'Save Changes',
    btn_view: 'View',
    btn_confirm: 'Confirm',
  },

  es: {
    // ── Navigation ──────────────────────────────────────────
    nav_dashboard: 'Panel',
    nav_workOrders: 'Órdenes de Trabajo',
    nav_history: 'Historial',
    nav_users: 'Usuarios',
    nav_support: 'Soporte',
    nav_logout: 'Cerrar sesión',
    nav_devices: 'Dispositivos',
    nav_mapRadiation: 'Mapa de Radiación',
    nav_alarms: 'Alarmas',
    nav_profile: 'Mi Perfil',
    nav_mySchedule: 'Mi Horario',
    nav_techPortal: 'Portal del Técnico',
    nav_techTagline: 'Vigilancia y Control',

    // ── Topbar ──────────────────────────────────────────────
    topbar_brand: 'EmSafe',
    topbar_role: 'Administrador',
    topbar_role_tech: 'Técnico',

    // ── Login ────────────────────────────────────────────────
    login_email: 'Correo electrónico',
    login_emailPlaceholder: 'alex@emsafe.com',
    login_password: 'Contraseña',
    login_forgotPassword: '¿Olvidó su contraseña?',
    login_remember: 'Recordar este dispositivo',
    login_signIn: 'Iniciar sesión',
    login_or: 'O',
    login_google: 'Iniciar con Google',
    login_error: 'Correo o contraseña incorrectos.',
    login_required: 'Ingrese su correo y contraseña.',
    login_footer: '© 2026 EmSafe Technologies. Todos los derechos reservados.',

    // ── Tech Schedule ────────────────────────────────────────
    tech_sched_title: 'Portal del Técnico',
    tech_sched_subtitle: 'Operaciones de Campo y Control',
    tech_sched_week: 'Semana',
    tech_sched_day: 'Día',
    tech_sched_filters: 'Filtros',
    tech_sched_today: 'Hoy',
    tech_sched_noTasks: 'Sin tareas programadas',
    tech_sched_priorityTask: 'TAREA PRIORITARIA',
    tech_sched_priorityTasks: 'TAREAS PRIORITARIAS',
    tech_sched_noPriority: 'No hay tareas urgentes pendientes.',
    tech_sched_weekProgress: 'PROGRESO SEMANAL',
    tech_sched_tasksCompleted: 'Tareas Completadas',

    // ── Tech Work Orders ─────────────────────────────────────
    tech_wo_search: 'Buscar por cliente o ID...',
    tech_wo_allOrders: 'Todas',
    tech_wo_serviceType: 'Tipo de Servicio',
    tech_wo_export: 'Exportar Informe',

    // ── Tech Work Order Detail ───────────────────────────────
    tech_detail_startJob: 'Iniciar Trabajo',
    tech_detail_saveChanges: 'Guardar Cambios',
    tech_detail_markCompleted: 'Marcar como Completado',
    tech_detail_generalInfo: 'Información General',
    tech_detail_clientContact: 'Contacto del Cliente',
    tech_detail_serviceInfo: 'Info del Servicio',
    tech_detail_locationMap: 'Mapa de Ubicación',
    tech_detail_sensorInstall: 'Instalación de Sensores (Requerido)',
    tech_detail_numSensors: 'Número de sensores instalados',
    tech_detail_sensorType: 'Tipo de Sensor',
    tech_detail_uploadProof: 'Subir Prueba de Instalación',
    tech_detail_dragDrop: 'Arrastra o haz clic para subir fotos',
    tech_detail_sensorCheck: 'Verificación de Sensores',
    tech_detail_techNotes: 'Notas del Técnico',
    tech_detail_updateStatus: 'Actualizar Estado',
    tech_detail_callClient: 'Llamar al Cliente',
    tech_detail_emailClient: 'Enviar Correo',
    tech_detail_activityLog: 'REGISTRO DE ACTIVIDAD',
    tech_detail_scheduledDate: 'Fecha Programada',
    tech_detail_priority: 'Prioridad',
    tech_detail_requiredTools: 'Herramientas Requeridas',
    tech_detail_expectedSensors: 'Esperado:',
    tech_detail_accessInstructions: 'Instrucciones de Acceso',
    tech_detail_deviceCheck: 'Verificación de Dispositivos',
    tech_detail_maintActions: 'Acciones de Mantenimiento',
    tech_detail_deviceRemoval: 'Retiro de Dispositivos',
    tech_detail_uploadEvidence: 'Subir Evidencia',
    tech_detail_devicesRequiring: 'Dispositivos que Requieren Mantenimiento',
    tech_detail_clientDevices: 'Dispositivos del Cliente',
    tech_detail_sensorInfo: 'Información de Sensores',
    tech_detail_deviceName: 'Nombre del Dispositivo',
    tech_detail_serial: 'Número de Serie',
    tech_detail_observation: 'Observación',
    tech_detail_removed: 'Retirado',
    tech_detail_action: 'Acción',
    tech_detail_description: 'Descripción',
    tech_detail_device: 'Dispositivo',
    tech_detail_completionDate: 'Fecha de Finalización',
    tech_detail_evidence: 'Evidencia',
    tech_detail_noDevices: 'Sin dispositivos.',
    tech_detail_addDeviceHint: 'Haz clic en + para agregar un sensor instalado.',
    tech_detail_discoverTitle: 'Descubrir Sensores (Requerido)',
    tech_detail_discoverHint: 'Enciende los sensores en el sitio — aparecen aquí a medida que reportan. Elige los que tienes enfrente (la lectura en vivo reacciona al mover el sensor) y ponles nombre.',
    tech_detail_discoverEmpty: 'Aún no se detectan sensores. Enciende un sensor y espera a que reporte.',
    tech_detail_live: 'En vivo',
    tech_detail_lastSeen: 'visto hace',
    wod_title: 'Orden de Trabajo',

    // ── Common buttons ──────────────────────────────────────
    btn_cancel: 'Cancelar',
    btn_create: 'Crear',
    btn_update: 'Guardar cambios',
    btn_save: 'Guardar cliente',
    btn_saveChanges: 'Guardar cambios',
    dev_createDevice: 'Crear dispositivo',
    btn_submit: 'Enviar',
    btn_edit: 'Editar',
    btn_delete: 'Eliminar',
    btn_backToList: 'Volver a la lista',
    btn_applyFilters: 'Aplicar filtros',
    btn_exportCsv: 'Exportar CSV',
    btn_exportReport: 'Exportar informe',
    btn_viewAll: 'Ver todo',
    btn_add: 'Agregar',

    // ── Common statuses ─────────────────────────────────────
    status_completed: 'Completado',
    status_inProgress: 'En progreso',
    status_pending: 'Pendiente',
    status_cancelled: 'Cancelado',
    status_active: 'Activo',
    status_inactive: 'Inactivo',
    status_maintenance: 'En mantenimiento',

    // ── Common table headers ─────────────────────────────────
    th_orderId: 'N° Orden',
    th_type: 'TIPO',
    th_client: 'CLIENTE',
    th_location: 'UBICACIÓN',
    th_date: 'FECHA',
    th_technician: 'TÉCNICO',
    th_status: 'ESTADO',
    th_actions: 'ACCIONES',
    th_siteLocation: 'SITIO',
    th_name: 'Nombre',
    th_role: 'Rol',
    th_email: 'Correo',
    th_completionDate: 'Fecha de completado',
    th_clientSite: 'Cliente / Sitio',
    th_serviceType: 'Tipo de servicio',
    th_leadTech: 'Técnico principal',

    // ── Dashboard ────────────────────────────────────────────
    dash_title: 'Resumen del Sistema',
    dash_subtitle: 'Monitoreo en tiempo real de radiación electromagnética y operaciones de campo.',
    dash_newWorkOrder: 'Nueva Orden de Trabajo',
    dash_totalSensors: 'TOTAL DE SENSORES',
    dash_totalDevices: 'DISPOSITIVOS',
    dash_activeClients: 'CLIENTES ACTIVOS',
    dash_totalUsers: 'USUARIOS',
    dash_pendingTasks: 'TAREAS PENDIENTES',
    dash_workOrders: 'ÓRDENES DE TRABAJO',
    dash_criticalAlerts: 'ALERTAS CRÍTICAS',
    dash_alarmsCount: 'ALARMAS',
    dash_systemActivity: 'Actividad del Sistema',
    dash_serviceHistory: 'Historial de Servicios',
    dash_serviceHistoryHint: 'Órdenes por tipo en 30 días',
    dash_activityHint: 'Órdenes generadas vs completadas en 30 días',
    dash_last30Days: 'Últimos 30 días',
    dash_radiationTrends: 'Tendencias de Radiación',
    dash_radiationHint: 'Niveles Prom. (µT)',
    dash_currentAvg: 'Promedio actual',
    dash_safetyThreshold: 'Umbral de seguridad',
    dash_safeMsg: 'Todos los sensores dentro de los límites seguros.',
    dash_latestOrders: 'Últimas Órdenes de Trabajo',
    dash_alerts: 'Alertas del Sistema',

    // ── Work Orders list ─────────────────────────────────────
    wo_title: 'Órdenes de Trabajo',
    wo_subtitle: 'Gestione y rastree despliegues de sensores electromagnéticos y registros de servicio.',
    wo_createNew: 'Crear nueva',
    wo_searchPlaceholder: 'Buscar órdenes, clientes o técnicos...',
    wo_typeAll: 'Tipo: Todos',
    filter_all: 'Todos',
    wo_installation: 'Instalación',
    wo_maintenance: 'Mantenimiento',
    wo_collection: 'Recolección',
    wo_statusAll: 'Estado: Todos',
    wo_showing: 'Mostrando 1-10 de 124 órdenes',
    wo_avgTime: 'TIEMPO PROM. DE COMPLETADO',
    wo_regional: 'ACTIVIDAD REGIONAL',
    wo_cancel: 'Cancelar Orden',
    wo_cancelReason: 'Motivo de cancelación',
    wo_cancelReasonEquip: 'Problema de equipo',
    wo_cancelReasonClient: 'Solicitud del cliente',
    wo_cancelReasonWeather: 'Condiciones climáticas',
    wo_cancelReasonOther: 'Otro',
    wo_cancelSuccess: 'Orden cancelada.',
    wo_selectReason: 'Selecciona un motivo',
    wo_sortBy: 'Ordenar por',
    wo_sortDate: 'Fecha más próxima',
    wo_sortCreated: 'Más reciente',
    wo_deleteConfirm: '¿Eliminar esta orden de trabajo?',
    wo_edit: 'Editar Orden',

    // ── New Work Order form ──────────────────────────────────
    wo_new_breadcrumb: 'Órdenes de Trabajo › Crear nueva',
    wo_new_title: 'Nueva Orden de Trabajo',
    wo_new_editBreadcrumb: 'Órdenes de Trabajo › Editar',
    wo_new_editTitle: 'Editar Orden de Trabajo',
    wo_new_subtitle: 'Registre una nueva inspección de seguridad electromagnética o tarea de mantenimiento.',
    wo_new_sectionTitle: 'Detalles de la Orden',
    wo_new_type: 'Tipo de Orden de Trabajo',
    wo_new_selectType: 'Seleccionar tipo...',
    wo_new_clientName: 'Nombre del cliente',
    wo_new_searchClient: 'Buscar en base de clientes...',
    wo_new_location: 'Dirección de ubicación',
    wo_new_locationPlaceholder: 'Buscar dirección en Perú...',
    wo_new_scheduledDate: 'Fecha programada',
    wo_new_scheduledTime: 'Hora programada',
    wo_new_assignedTech: 'Técnico asignado',
    wo_new_selectTech: 'Seleccionar técnico...',
    wo_new_notes: 'Notas',
    wo_new_notesPlaceholder: 'Descripción detallada del servicio requerido o anomalías observadas...',
    wo_new_pickLocation: 'Seleccionar ubicación en el mapa',
    wo_new_pickLocationHint: 'Haz clic en cualquier punto del mapa para seleccionar la ubicación exacta.',
    wo_new_noLocationSelected: 'Sin ubicación seleccionada — haz clic en el mapa',
    wo_new_confirmLocation: 'Confirmar ubicación',

    // ── History ──────────────────────────────────────────────
    hist_title: 'Historial de Órdenes de Trabajo',
    hist_subtitle: 'Órdenes de trabajo completadas y canceladas',
    hist_dateRange: 'Rango de fechas',
    hist_type: 'Tipo',
    hist_technician: 'Técnico',
    hist_allTypes: 'Todos los tipos',
    hist_allPersonnel: 'Todo el personal',
    hist_showing: 'Mostrando 1 - 5 de 142 resultados',
    hist_from: 'Desde',
    hist_to: 'Hasta',
    hist_clearDates: 'Limpiar',
    hist_view: 'Ver Detalles',
    hist_detail_title: 'Detalles de la Orden',
    hist_detail_completedBy: 'Completado por',
    hist_detail_completionDate: 'Fecha de completado',
    hist_detail_notes: 'Notas del administrador',
    hist_detail_cancellationReason: 'Motivo de cancelación',
    hist_detail_sensorsInstalled: 'Sensores instalados',
    hist_detail_techNotes: 'Notas del técnico',
    hist_detail_noNotes: 'Sin notas registradas.',

    // ── Users / Team Management ──────────────────────────────
    users_title: 'Gestión de Equipo',
    users_subtitle: 'Gestione admins, técnicos y clientes registrados de la plataforma.',
    users_totalUsers: 'TOTAL DE USUARIOS',
    users_activeNow: 'ACTIVOS AHORA',
    users_activeSub: 'Usuarios',
    users_activeClients: 'CLIENTES ACTIVOS',
    users_activeClientsSub: 'Clientes registrados',
    users_inactiveClients: 'CLIENTES INACTIVOS',
    users_inactiveClientsSub: 'Necesitan atención',
    users_clearFilters: 'Limpiar filtros',
    users_viewClient: 'Ver Cliente',
    users_activate: 'Activar cuenta',
    vc_title: 'Perfil del Cliente',
    vc_devices: 'Dispositivos',
    vc_noDevices: 'Este cliente no tiene dispositivos.',
    vc_notFound: 'Cliente no encontrado.',
    users_pendingApproval: 'APROBACIÓN PENDIENTE',
    users_pendingSub: 'Acción requerida',
    users_activated: 'Usuario activado',
    users_activateFail: 'No se pudo activar el usuario',
    users_deleted: 'Usuario eliminado correctamente',
    users_confirmDelete: '¿Seguro que deseas eliminar este usuario?',
    users_systemHealth: 'SALUD DEL SISTEMA',
    users_healthSub: 'Óptimo',
    users_allUsers: 'Todos',
    users_admins: 'Admins',
    users_technicians: 'Técnicos',
    users_clients: 'Clientes',
    users_searchPlaceholder: 'Buscar miembros del equipo...',
    users_addModalTitle: 'Agregar nuevo usuario',
    users_addModalDesc: 'Selecciona el tipo de usuario que deseas agregar a la plataforma.',
    users_addAdmin: 'Admin',
    users_addAdminDesc: 'Operador con acceso total al sistema',
    users_addTechnician: 'Técnico',
    users_addTechDesc: 'Operador de servicio de campo',
    users_addClient: 'Cliente',
    users_addClientDesc: 'Entidad externa con acceso a sensores',
    users_joinDate: 'Fecha de ingreso',

    // ── Create Admin form ────────────────────────────────────
    admin_breadcrumb: 'Usuarios › Crear nuevo Admin',
    admin_title: 'Crear nuevo Admin',
    admin_editTitle: 'Editar Admin',
    admin_sectionTitle: 'Datos del Admin',
    admin_sectionDesc: 'Ingrese la información para crear un nuevo operador del sistema.',

    // ── Create Technician form ───────────────────────────────
    tech_breadcrumb: 'Usuarios › Crear nuevo Técnico',
    tech_title: 'Crear nuevo Técnico',
    tech_editTitle: 'Editar Técnico',
    tech_sectionTitle: 'Datos del Técnico',
    tech_sectionDesc: 'Ingrese la información para crear un nuevo operador de campo.',

    // ── Common form fields ───────────────────────────────────
    form_fullName: 'Nombre completo',
    form_emailAddress: 'Correo electrónico',
    form_phone: 'Número de teléfono',
    form_password: 'Contraseña',
    form_confirmPassword: 'Confirmar contraseña',
    form_additionalNotes: 'Notas adicionales',
    form_notesPlaceholder: 'Ingrese notas administrativas sobre esta cuenta de usuario...',
    form_activationMsg: 'Los nuevos usuarios recibirán un correo de activación con sus credenciales temporales e instrucciones para la primera configuración de seguridad.',
    form_status: 'Estado de la cuenta',
    form_statusActive: 'Activo (marcar para activar, desmarcar para inactivo)',
    form_statusInactive: 'Inactivo',
    form_statusHint: 'Si no está marcado, la cuenta se creará como inactiva.',

    // ── Edit Client form ─────────────────────────────────────
    client_edit_breadcrumb: 'Usuarios › Editar cliente',
    client_new_breadcrumb: 'Usuarios › Nuevo cliente',
    client_edit_title: 'Editar cliente',
    client_new_title: 'Nuevo Cliente',
    client_edit_subtitle: 'Registre o actualice un cliente.',
    client_type: 'Tipo de cliente',
    client_company: 'Empresa',
    client_individual: 'Individual',
    client_info: 'Información del cliente',
    client_companyName: 'Nombre de la empresa',
    client_taxId: 'CUIT / Tax ID',
    client_ruc: 'RUC',
    client_industry: 'Industria',
    client_selectIndustry: 'Seleccionar industria...',
    client_fullName: 'Nombre completo',
    client_docId: 'DNI / N° de documento',
    client_location: 'Ubicación',
    client_address: 'Dirección',
    client_city: 'Ciudad',
    client_country: 'País',
    client_primaryContact: 'Contacto principal',
    client_contactName: 'Nombre del contacto',
    client_contactEmail: 'Correo',
    client_contactPhone: 'Teléfono',
    client_sensorInfo: 'Información de sensores',
    client_numSensors: 'Cantidad de sensores instalados',
    client_sensorType: 'Tipo de sensor',
    client_appAccess: 'Acceso a la app',
    client_enableApp: 'Habilitar acceso a la app',
    client_accessEmail: 'Correo de acceso',
    client_prefilled: 'Completado desde contacto principal',
    client_statusNotes: 'Estado y notas',
    client_initialStatus: 'Estado',
    client_internalNotes: 'Notas internas',
    client_internalPlaceholder: 'Ingrese requisitos específicos o información de contexto...',
    client_active: 'Activo',
    client_inactive: 'Inactivo',

    // ── Profile page ─────────────────────────────────────────────────────────────
    profile_title: 'Mi Perfil',
    profile_subtitle: 'Visualiza y actualiza la información de tu cuenta.',
    profile_personalInfo: 'Información Personal',
    profile_security: 'Seguridad',
    profile_currentPassword: 'Contraseña actual',
    profile_newPassword: 'Nueva contraseña',
    profile_confirmNew: 'Confirmar nueva contraseña',
    profile_changePassword: 'Cambiar contraseña',
    profile_savedOk: 'Perfil actualizado correctamente.',
    profile_pwOk: 'Contraseña cambiada correctamente.',
    profile_pwError: 'Error al cambiar contraseña. Verifica tu contraseña actual.',

    // ── Devices page ─────────────────────────────────────────────────────────────
    dev_title: 'Dispositivos',
    dev_subtitle: 'Gestión de sensores electromagnéticos y equipos de monitoreo.',
    dev_addDevice: 'Agregar dispositivo',
    dev_editDevice: 'Editar dispositivo',
    dev_name: 'Nombre del dispositivo',
    dev_type: 'Tipo',
    dev_location: 'Ubicación',
    dev_status: 'Estado',
    dev_serial: 'Número de serie',
    dev_installDate: 'Fecha de instalación',
    dev_selectType: 'Seleccionar tipo...',
    dev_sensor: 'Sensor',
    dev_gateway: 'Gateway',
    dev_monitor: 'Monitor',
    dev_controller: 'Controlador',
    dev_plug: 'Enchufe',
    dev_actuator: 'Actuador',
    dev_active: 'Activo',
    dev_inactive: 'Inactivo',
    dev_inMaintenance: 'En mantenimiento',
    dev_requiresMaintenance: 'Requiere mantenimiento',
    dev_collecting: 'Recolectando',
    dev_confirmDelete: '¿Eliminar este dispositivo?',
    dev_noDevices: 'No se encontraron dispositivos.',
    dev_client: 'Cliente asociado',
    dev_viewClient: 'Ver cliente',
    dev_createWorkOrder: 'Crear orden de trabajo',
    dev_searchPlaceholder: 'Buscar por nombre o serie...',
    dev_filterAll: 'Todos',
    dev_filterByClient: 'Cliente: Todos',
    dev_filterByType: 'Tipo: Todos',
    dev_filterByStatus: 'Estado: Todos',

    // ── Alarms page ───────────────────────────────────────────────────────────────
    alarm_title: 'Alarmas',
    alarm_subtitle: 'Monitorea y gestiona alertas y notificaciones del sistema.',
    alarm_addAlarm: 'Nueva alarma',
    alarm_resolve: 'Resolver',
    alarm_resolved: 'Resuelta',
    alarm_unresolved: 'Sin resolver',
    alarm_all: 'Todas',
    alarm_sensorAlarms: 'Alarmas de Sensores',
    alarm_systemAlerts: 'Alertas del Sistema',
    alarm_allClients: 'Todos los clientes',
    alarm_titleField: 'Título',
    alarm_description: 'Descripción',
    alarm_type: 'Tipo',
    alarm_confirmDelete: '¿Eliminar esta alarma?',
    alarm_noAlarms: 'No se encontraron alarmas.',
    alarm_icon: 'Clase de ícono (opcional)',
    alarm_danger: 'Crítica',
    alarm_info: 'Información',
    alarm_success: 'Éxito',
    alarm_warning: 'Advertencia',
    alarm_recipients: 'Destinatarios',
    alarm_allUsers: 'Todos los usuarios',
    alarm_specificUsers: 'Usuarios específicos',
    alarm_detail_title: 'Detalles de la Alarma',
    alarm_client: 'Cliente',
    alarm_filterByClient: 'Cliente: Todos',
    alarm_sensor: 'Sensor',
    alarm_time: 'Tiempo',
    alarm_sensorPlaceholder: 'ej. #LM-012 (opcional)',
    alarm_clientHint: 'Mantén Ctrl/Cmd para seleccionar varios clientes.',
    btn_close: 'Cerrar',

    // ── Radiation Map page ────────────────────────────────────────────────────────
    map_title: 'Mapa de Radiación',
    map_subtitle: 'Distribución geográfica de lecturas de radiación electromagnética.',
    map_sensor: 'Sensor',
    map_value: 'Valor (µT)',
    map_date: 'Fecha',
    map_location: 'Ubicación',
    map_noData: 'No hay datos de radiación disponibles.',
    map_listView: 'Vista de lista',
    map_legend: 'Leyenda',
    map_safe: 'Seguro',
    map_caution: 'Precaución',
    map_danger: 'Peligro',
    map_client: 'Cliente',
    map_zone: 'Zona / Área',
    map_clickHint: 'Haz clic en un marcador para ver detalles del cliente',

    // ── Topbar ──────────────────────────────────────────────
    topbar_preferences: 'Preferencias',
    topbar_darkMode: 'Modo oscuro',
    topbar_fontSize: 'Tamaño de fuente',
    topbar_fontSmall: 'Pequeño',
    topbar_fontMedium: 'Mediano',
    topbar_fontLarge: 'Grande',
    topbar_myProfile: 'Mi Perfil',
    topbar_recentActivity: 'Actividad Reciente',
    topbar_noActivity: 'Sin actividad reciente',

    btn_saveProfile: 'Guardar cambios',
    btn_view: 'Ver',
    btn_confirm: 'Confirmar',
  },
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  private _lang = signal<Lang>('en');
  readonly lang = this._lang.asReadonly();

  toggle(): void {
    this._lang.update(l => (l === 'en' ? 'es' : 'en'));
  }

  t(key: string): string {
    return TRANSLATIONS[this._lang()][key] ?? key;
  }
}
