import { Injectable, signal } from '@angular/core';

export type Lang = 'en' | 'es';

const TRANSLATIONS: Record<Lang, Record<string, string>> = {
  en: {
    // ── Navigation ──────────────────────────────────────────
    nav_dashboard: 'Dashboard',
    nav_workOrders: 'Work Orders',
    nav_history: 'History',
    nav_users: 'Users',
    nav_support: 'Support',
    nav_logout: 'Logout',
    nav_mySchedule: 'My Schedule',
    nav_techPortal: 'Technician Portal',
    nav_techTagline: 'Vigilance & Control',

    // ── Topbar ──────────────────────────────────────────────
    topbar_brand: 'EmSafe',
    topbar_role: 'System Admin',
    topbar_role_tech: 'Technician',

    // ── Login ────────────────────────────────────────────────
    login_email: 'Email Address',
    login_emailPlaceholder: 'alex@emsafe.com',
    login_password: 'Password',
    login_forgotPassword: 'Forgot Password?',
    login_remember: 'Remember this device',
    login_signIn: 'Sign In',
    login_or: 'OR',
    login_google: 'Sign in with Google',
    login_error: 'Invalid email or password.',
    login_required: 'Please enter your email and password.',
    login_footer: '© 2026 EmSafe Technologies. All rights reserved.',

    // ── Tech Schedule ────────────────────────────────────────
    tech_sched_title: 'Technician Portal',
    tech_sched_subtitle: 'Field Operations & Control',
    tech_sched_week: 'Week',
    tech_sched_day: 'Day',
    tech_sched_filters: 'Filters',
    tech_sched_today: 'Today',
    tech_sched_noTasks: 'No tasks scheduled',
    tech_sched_priorityTask: 'PRIORITY TASK',
    tech_sched_weekProgress: 'WEEK PROGRESS',
    tech_sched_tasksCompleted: 'Tasks Completed',

    // ── Tech Work Orders ─────────────────────────────────────
    tech_wo_search: 'Search by client name or ID...',
    tech_wo_allOrders: 'All Orders',
    tech_wo_serviceType: 'Service Type',
    tech_wo_export: 'Export Report',

    // ── Tech Work Order Detail ───────────────────────────────
    tech_detail_startJob: 'Start Job',
    tech_detail_saveChanges: 'Save Changes',
    tech_detail_markCompleted: 'Mark as Completed',
    tech_detail_generalInfo: 'General Info',
    tech_detail_clientContact: 'Client Contact',
    tech_detail_serviceInfo: 'Service Info',
    tech_detail_sensorInstall: 'Sensor Installation (Required)',
    tech_detail_numSensors: 'Number of sensors installed',
    tech_detail_sensorType: 'Sensor Type',
    tech_detail_uploadProof: 'Upload Installation Proof',
    tech_detail_dragDrop: 'Drag and drop or click to upload photos',
    tech_detail_sensorCheck: 'Sensor Check',
    tech_detail_techNotes: 'Technician Notes',
    tech_detail_updateStatus: 'Update Status',
    tech_detail_callClient: 'Call Client',
    tech_detail_emailClient: 'Email Client',
    tech_detail_activityLog: 'ACTIVITY LOG',
    tech_detail_scheduledDate: 'Scheduled Date',
    tech_detail_priority: 'Priority',
    tech_detail_requiredTools: 'Required Tools',
    tech_detail_expectedSensors: 'Expected:',
    tech_detail_accessInstructions: 'Access Instructions',

    // ── Common buttons ──────────────────────────────────────
    btn_cancel: 'Cancel',
    btn_create: 'Create',
    btn_save: 'Save Client',
    btn_submit: 'Submit',
    btn_edit: 'Edit',
    btn_delete: 'Delete',
    btn_backToList: 'Back to List',
    btn_applyFilters: 'Apply Filters',
    btn_exportCsv: 'Export CSV',
    btn_exportReport: 'Export Report',
    btn_viewAll: 'View All',
    btn_add: 'Add',

    // ── Common statuses ─────────────────────────────────────
    status_completed: 'Completed',
    status_inProgress: 'In progress',
    status_pending: 'Pending',
    status_cancelled: 'Cancelled',
    status_active: 'Active',
    status_inactive: 'Inactive',

    // ── Common table headers ─────────────────────────────────
    th_orderId: 'Order ID',
    th_type: 'TYPE',
    th_client: 'CLIENT',
    th_location: 'LOCATION',
    th_date: 'DATE',
    th_technician: 'TECHNICIAN',
    th_status: 'STATUS',
    th_actions: 'ACTIONS',
    th_siteLocation: 'SITE LOCATION',
    th_name: 'Name',
    th_role: 'Role',
    th_email: 'Email',
    th_completionDate: 'Completion Date',
    th_clientSite: 'Client / Site',
    th_serviceType: 'Service Type',
    th_leadTech: 'Lead Technician',

    // ── Dashboard ────────────────────────────────────────────
    dash_title: 'System Overview',
    dash_subtitle: 'Real-time monitoring of electromagnetic radiation and field operations.',
    dash_newWorkOrder: 'New Work Order',
    dash_totalSensors: 'TOTAL SENSORS',
    dash_activeClients: 'ACTIVE CLIENTS',
    dash_pendingTasks: 'PENDING TASKS',
    dash_criticalAlerts: 'CRITICAL ALERTS',
    dash_systemActivity: 'System Activity',
    dash_activityHint: 'Work orders generated vs completed over 30 days',
    dash_last30Days: 'Last 30 Days',
    dash_radiationTrends: 'Radiation Trends',
    dash_radiationHint: 'Avg. Levels (μSv/h)',
    dash_currentAvg: 'Current Avg.',
    dash_safetyThreshold: 'Safety Threshold',
    dash_safeMsg: 'All sensors within safety limits.',
    dash_latestOrders: 'Latest Work Orders',
    dash_alerts: 'System Alerts',

    // ── Work Orders list ─────────────────────────────────────
    wo_title: 'Work Orders',
    wo_subtitle: 'Manage and track electromagnetic sensor deployments and field service logs.',
    wo_createNew: 'Create New',
    wo_searchPlaceholder: 'Search work orders, clients or tech ID...',
    wo_typeAll: 'Type: All',
    wo_installation: 'Installation',
    wo_maintenance: 'Maintenance',
    wo_collection: 'Collection',
    wo_statusAll: 'Status: All',
    wo_showing: 'Showing 1-10 of 124 orders',
    wo_avgTime: 'AVG. COMPLETION TIME',
    wo_regional: 'REGIONAL ACTIVITY',

    // ── New Work Order form ──────────────────────────────────
    wo_new_breadcrumb: 'Work Orders › Create New',
    wo_new_title: 'New Work Order',
    wo_new_subtitle: 'Register a new electromagnetic safety inspection or sensor maintenance task.',
    wo_new_sectionTitle: 'Work Order Details',
    wo_new_type: 'Work Order Type',
    wo_new_selectType: 'Select Type...',
    wo_new_clientName: 'Client Name',
    wo_new_searchClient: 'Search client database...',
    wo_new_location: 'Location Address',
    wo_new_locationPlaceholder: 'Street, Building, Floor or GPS coordinates',
    wo_new_scheduledDate: 'Scheduled Date & Time',
    wo_new_assignedTech: 'Assigned Technician',
    wo_new_selectTech: 'Select Technician...',
    wo_new_notes: 'Notes',
    wo_new_notesPlaceholder: 'Detailed description of the required service or observed anomalies...',

    // ── History ──────────────────────────────────────────────
    hist_title: 'Work Orders History',
    hist_subtitle: 'Completed and Cancelled Work orders',
    hist_dateRange: 'Date Range',
    hist_type: 'Type',
    hist_technician: 'Technician',
    hist_allTypes: 'All Types',
    hist_allPersonnel: 'All Personnel',
    hist_showing: 'Showing 1 - 5 of 142 results',
    hist_from: 'From',
    hist_to: 'To',
    hist_clearDates: 'Clear',

    // ── Users / Team Management ──────────────────────────────
    users_title: 'Team Management',
    users_subtitle: 'Manage platform access, roles, and safety technician assignments.',
    users_totalUsers: 'TOTAL USERS',
    users_activeNow: 'ACTIVE NOW',
    users_activeSub: 'Users',
    users_pendingApproval: 'PENDING APPROVAL',
    users_pendingSub: 'Action Required',
    users_systemHealth: 'SYSTEM HEALTH',
    users_healthSub: 'Optimal',
    users_allUsers: 'All Users',
    users_admins: 'Admins',
    users_technicians: 'Technicians',
    users_clients: 'Clients',
    users_searchPlaceholder: 'Search team members...',
    users_addModalTitle: 'Add New User',
    users_addModalDesc: 'Select the type of user you want to add to the platform.',
    users_addAdmin: 'Admin',
    users_addAdminDesc: 'System operator with full access',
    users_addTechnician: 'Technician',
    users_addTechDesc: 'Field service operator',
    users_addClient: 'Client',
    users_addClientDesc: 'External entity with sensor access',

    // ── Create Admin form ────────────────────────────────────
    admin_breadcrumb: 'Users › Create New Admin',
    admin_title: 'Create New Admin',
    admin_sectionTitle: 'Admin Details',
    admin_sectionDesc: 'Enter the information to provision a new system operator.',

    // ── Create Technician form ───────────────────────────────
    tech_breadcrumb: 'Users › Create New Technician',
    tech_title: 'Create New Technician',
    tech_sectionTitle: 'Technician Details',
    tech_sectionDesc: 'Enter the information to provision a new field operator.',

    // ── Common form fields ───────────────────────────────────
    form_fullName: 'Full Name',
    form_emailAddress: 'Email Address',
    form_phone: 'Phone Number',
    form_password: 'Password',
    form_confirmPassword: 'Confirm Password',
    form_additionalNotes: 'Additional Notes',
    form_notesPlaceholder: 'Enter any administrative notes regarding this user account...',
    form_activationMsg: 'Newly created users will receive an activation email with their temporary credentials and instructions for the first login security setup.',

    // ── Edit Client form ─────────────────────────────────────
    client_edit_breadcrumb: 'Users › Edit Client',
    client_edit_title: 'Edit Client',
    client_edit_subtitle: 'Register a new client entity and configure initial sensor parameters.',
    client_type: 'Client Type',
    client_company: 'Company',
    client_individual: 'Individual',
    client_info: 'Client Information',
    client_companyName: 'Company Name',
    client_taxId: 'Tax ID',
    client_industry: 'Industry',
    client_selectIndustry: 'Select an industry...',
    client_fullName: 'Full Name',
    client_docId: 'ID / Document Number',
    client_location: 'Location',
    client_address: 'Address',
    client_city: 'City',
    client_country: 'Country',
    client_primaryContact: 'Primary Contact',
    client_contactName: 'Contact Name',
    client_contactEmail: 'Email',
    client_contactPhone: 'Phone',
    client_sensorInfo: 'Sensor Information',
    client_numSensors: 'Number of Installed Sensors',
    client_sensorType: 'Sensor Type',
    client_appAccess: 'App Access',
    client_enableApp: 'Enable App Access',
    client_accessEmail: 'Access Email',
    client_prefilled: 'Prefilled from primary contact',
    client_statusNotes: 'Status & Notes',
    client_initialStatus: 'Initial Status',
    client_internalNotes: 'Internal Notes',
    client_internalPlaceholder: 'Enter any specific requirements or background information here...',
  },

  es: {
    // ── Navigation ──────────────────────────────────────────
    nav_dashboard: 'Panel',
    nav_workOrders: 'Órdenes de Trabajo',
    nav_history: 'Historial',
    nav_users: 'Usuarios',
    nav_support: 'Soporte',
    nav_logout: 'Cerrar sesión',
    nav_mySchedule: 'Mi Horario',
    nav_techPortal: 'Portal del Técnico',
    nav_techTagline: 'Vigilancia y Control',

    // ── Topbar ──────────────────────────────────────────────
    topbar_brand: 'EmSafe',
    topbar_role: 'Administrador',
    topbar_role_tech: 'Técnico',

    // ── Login ────────────────────────────────────────────────
    login_email: 'Correo electrónico',
    login_emailPlaceholder: 'alex@emsafe.com',
    login_password: 'Contraseña',
    login_forgotPassword: '¿Olvidó su contraseña?',
    login_remember: 'Recordar este dispositivo',
    login_signIn: 'Iniciar sesión',
    login_or: 'O',
    login_google: 'Iniciar con Google',
    login_error: 'Correo o contraseña incorrectos.',
    login_required: 'Ingrese su correo y contraseña.',
    login_footer: '© 2026 EmSafe Technologies. Todos los derechos reservados.',

    // ── Tech Schedule ────────────────────────────────────────
    tech_sched_title: 'Portal del Técnico',
    tech_sched_subtitle: 'Operaciones de Campo y Control',
    tech_sched_week: 'Semana',
    tech_sched_day: 'Día',
    tech_sched_filters: 'Filtros',
    tech_sched_today: 'Hoy',
    tech_sched_noTasks: 'Sin tareas programadas',
    tech_sched_priorityTask: 'TAREA PRIORITARIA',
    tech_sched_weekProgress: 'PROGRESO SEMANAL',
    tech_sched_tasksCompleted: 'Tareas Completadas',

    // ── Tech Work Orders ─────────────────────────────────────
    tech_wo_search: 'Buscar por cliente o ID...',
    tech_wo_allOrders: 'Todas',
    tech_wo_serviceType: 'Tipo de Servicio',
    tech_wo_export: 'Exportar Informe',

    // ── Tech Work Order Detail ───────────────────────────────
    tech_detail_startJob: 'Iniciar Trabajo',
    tech_detail_saveChanges: 'Guardar Cambios',
    tech_detail_markCompleted: 'Marcar como Completado',
    tech_detail_generalInfo: 'Información General',
    tech_detail_clientContact: 'Contacto del Cliente',
    tech_detail_serviceInfo: 'Info del Servicio',
    tech_detail_sensorInstall: 'Instalación de Sensores (Requerido)',
    tech_detail_numSensors: 'Número de sensores instalados',
    tech_detail_sensorType: 'Tipo de Sensor',
    tech_detail_uploadProof: 'Subir Prueba de Instalación',
    tech_detail_dragDrop: 'Arrastra o haz clic para subir fotos',
    tech_detail_sensorCheck: 'Verificación de Sensores',
    tech_detail_techNotes: 'Notas del Técnico',
    tech_detail_updateStatus: 'Actualizar Estado',
    tech_detail_callClient: 'Llamar al Cliente',
    tech_detail_emailClient: 'Enviar Correo',
    tech_detail_activityLog: 'REGISTRO DE ACTIVIDAD',
    tech_detail_scheduledDate: 'Fecha Programada',
    tech_detail_priority: 'Prioridad',
    tech_detail_requiredTools: 'Herramientas Requeridas',
    tech_detail_expectedSensors: 'Esperado:',
    tech_detail_accessInstructions: 'Instrucciones de Acceso',

    // ── Common buttons ──────────────────────────────────────
    btn_cancel: 'Cancelar',
    btn_create: 'Crear',
    btn_save: 'Guardar cliente',
    btn_submit: 'Enviar',
    btn_edit: 'Editar',
    btn_delete: 'Eliminar',
    btn_backToList: 'Volver a la lista',
    btn_applyFilters: 'Aplicar filtros',
    btn_exportCsv: 'Exportar CSV',
    btn_exportReport: 'Exportar informe',
    btn_viewAll: 'Ver todo',
    btn_add: 'Agregar',

    // ── Common statuses ─────────────────────────────────────
    status_completed: 'Completado',
    status_inProgress: 'En progreso',
    status_pending: 'Pendiente',
    status_cancelled: 'Cancelado',
    status_active: 'Activo',
    status_inactive: 'Inactivo',

    // ── Common table headers ─────────────────────────────────
    th_orderId: 'N° Orden',
    th_type: 'TIPO',
    th_client: 'CLIENTE',
    th_location: 'UBICACIÓN',
    th_date: 'FECHA',
    th_technician: 'TÉCNICO',
    th_status: 'ESTADO',
    th_actions: 'ACCIONES',
    th_siteLocation: 'SITIO',
    th_name: 'Nombre',
    th_role: 'Rol',
    th_email: 'Correo',
    th_completionDate: 'Fecha de completado',
    th_clientSite: 'Cliente / Sitio',
    th_serviceType: 'Tipo de servicio',
    th_leadTech: 'Técnico principal',

    // ── Dashboard ────────────────────────────────────────────
    dash_title: 'Resumen del Sistema',
    dash_subtitle: 'Monitoreo en tiempo real de radiación electromagnética y operaciones de campo.',
    dash_newWorkOrder: 'Nueva Orden de Trabajo',
    dash_totalSensors: 'TOTAL DE SENSORES',
    dash_activeClients: 'CLIENTES ACTIVOS',
    dash_pendingTasks: 'TAREAS PENDIENTES',
    dash_criticalAlerts: 'ALERTAS CRÍTICAS',
    dash_systemActivity: 'Actividad del Sistema',
    dash_activityHint: 'Órdenes generadas vs completadas en 30 días',
    dash_last30Days: 'Últimos 30 días',
    dash_radiationTrends: 'Tendencias de Radiación',
    dash_radiationHint: 'Niveles Prom. (μSv/h)',
    dash_currentAvg: 'Promedio actual',
    dash_safetyThreshold: 'Umbral de seguridad',
    dash_safeMsg: 'Todos los sensores dentro de los límites seguros.',
    dash_latestOrders: 'Últimas Órdenes de Trabajo',
    dash_alerts: 'Alertas del Sistema',

    // ── Work Orders list ─────────────────────────────────────
    wo_title: 'Órdenes de Trabajo',
    wo_subtitle: 'Gestione y rastree despliegues de sensores electromagnéticos y registros de servicio.',
    wo_createNew: 'Crear nueva',
    wo_searchPlaceholder: 'Buscar órdenes, clientes o técnicos...',
    wo_typeAll: 'Tipo: Todos',
    wo_installation: 'Instalación',
    wo_maintenance: 'Mantenimiento',
    wo_collection: 'Recolección',
    wo_statusAll: 'Estado: Todos',
    wo_showing: 'Mostrando 1-10 de 124 órdenes',
    wo_avgTime: 'TIEMPO PROM. DE COMPLETADO',
    wo_regional: 'ACTIVIDAD REGIONAL',

    // ── New Work Order form ──────────────────────────────────
    wo_new_breadcrumb: 'Órdenes de Trabajo › Crear nueva',
    wo_new_title: 'Nueva Orden de Trabajo',
    wo_new_subtitle: 'Registre una nueva inspección de seguridad electromagnética o tarea de mantenimiento.',
    wo_new_sectionTitle: 'Detalles de la Orden',
    wo_new_type: 'Tipo de Orden de Trabajo',
    wo_new_selectType: 'Seleccionar tipo...',
    wo_new_clientName: 'Nombre del cliente',
    wo_new_searchClient: 'Buscar en base de clientes...',
    wo_new_location: 'Dirección de ubicación',
    wo_new_locationPlaceholder: 'Calle, Edificio, Piso o coordenadas GPS',
    wo_new_scheduledDate: 'Fecha y hora programada',
    wo_new_assignedTech: 'Técnico asignado',
    wo_new_selectTech: 'Seleccionar técnico...',
    wo_new_notes: 'Notas',
    wo_new_notesPlaceholder: 'Descripción detallada del servicio requerido o anomalías observadas...',

    // ── History ──────────────────────────────────────────────
    hist_title: 'Historial de Órdenes de Trabajo',
    hist_subtitle: 'Órdenes de trabajo completadas y canceladas',
    hist_dateRange: 'Rango de fechas',
    hist_type: 'Tipo',
    hist_technician: 'Técnico',
    hist_allTypes: 'Todos los tipos',
    hist_allPersonnel: 'Todo el personal',
    hist_showing: 'Mostrando 1 - 5 de 142 resultados',
    hist_from: 'Desde',
    hist_to: 'Hasta',
    hist_clearDates: 'Limpiar',

    // ── Users / Team Management ──────────────────────────────
    users_title: 'Gestión de Equipo',
    users_subtitle: 'Administre el acceso a la plataforma, roles y asignaciones de técnicos.',
    users_totalUsers: 'TOTAL DE USUARIOS',
    users_activeNow: 'ACTIVOS AHORA',
    users_activeSub: 'Usuarios',
    users_pendingApproval: 'APROBACIÓN PENDIENTE',
    users_pendingSub: 'Acción requerida',
    users_systemHealth: 'SALUD DEL SISTEMA',
    users_healthSub: 'Óptimo',
    users_allUsers: 'Todos',
    users_admins: 'Admins',
    users_technicians: 'Técnicos',
    users_clients: 'Clientes',
    users_searchPlaceholder: 'Buscar miembros del equipo...',
    users_addModalTitle: 'Agregar nuevo usuario',
    users_addModalDesc: 'Selecciona el tipo de usuario que deseas agregar a la plataforma.',
    users_addAdmin: 'Admin',
    users_addAdminDesc: 'Operador con acceso total al sistema',
    users_addTechnician: 'Técnico',
    users_addTechDesc: 'Operador de servicio de campo',
    users_addClient: 'Cliente',
    users_addClientDesc: 'Entidad externa con acceso a sensores',

    // ── Create Admin form ────────────────────────────────────
    admin_breadcrumb: 'Usuarios › Crear nuevo Admin',
    admin_title: 'Crear nuevo Admin',
    admin_sectionTitle: 'Datos del Admin',
    admin_sectionDesc: 'Ingrese la información para crear un nuevo operador del sistema.',

    // ── Create Technician form ───────────────────────────────
    tech_breadcrumb: 'Usuarios › Crear nuevo Técnico',
    tech_title: 'Crear nuevo Técnico',
    tech_sectionTitle: 'Datos del Técnico',
    tech_sectionDesc: 'Ingrese la información para crear un nuevo operador de campo.',

    // ── Common form fields ───────────────────────────────────
    form_fullName: 'Nombre completo',
    form_emailAddress: 'Correo electrónico',
    form_phone: 'Número de teléfono',
    form_password: 'Contraseña',
    form_confirmPassword: 'Confirmar contraseña',
    form_additionalNotes: 'Notas adicionales',
    form_notesPlaceholder: 'Ingrese notas administrativas sobre esta cuenta de usuario...',
    form_activationMsg: 'Los nuevos usuarios recibirán un correo de activación con sus credenciales temporales e instrucciones para la primera configuración de seguridad.',

    // ── Edit Client form ─────────────────────────────────────
    client_edit_breadcrumb: 'Usuarios › Editar cliente',
    client_edit_title: 'Editar cliente',
    client_edit_subtitle: 'Registre un nuevo cliente y configure los parámetros iniciales de sensores.',
    client_type: 'Tipo de cliente',
    client_company: 'Empresa',
    client_individual: 'Individual',
    client_info: 'Información del cliente',
    client_companyName: 'Nombre de la empresa',
    client_taxId: 'CUIT / Tax ID',
    client_industry: 'Industria',
    client_selectIndustry: 'Seleccionar industria...',
    client_fullName: 'Nombre completo',
    client_docId: 'N° de documento',
    client_location: 'Ubicación',
    client_address: 'Dirección',
    client_city: 'Ciudad',
    client_country: 'País',
    client_primaryContact: 'Contacto principal',
    client_contactName: 'Nombre del contacto',
    client_contactEmail: 'Correo',
    client_contactPhone: 'Teléfono',
    client_sensorInfo: 'Información de sensores',
    client_numSensors: 'Cantidad de sensores instalados',
    client_sensorType: 'Tipo de sensor',
    client_appAccess: 'Acceso a la app',
    client_enableApp: 'Habilitar acceso a la app',
    client_accessEmail: 'Correo de acceso',
    client_prefilled: 'Completado desde contacto principal',
    client_statusNotes: 'Estado y notas',
    client_initialStatus: 'Estado inicial',
    client_internalNotes: 'Notas internas',
    client_internalPlaceholder: 'Ingrese requisitos específicos o información de contexto...',
  },
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  private _lang = signal<Lang>('en');
  readonly lang = this._lang.asReadonly();

  toggle(): void {
    this._lang.update(l => (l === 'en' ? 'es' : 'en'));
  }

  t(key: string): string {
    return TRANSLATIONS[this._lang()][key] ?? key;
  }
}
